/*
Copyright (©) 2025 Thinh Truong Nguyen

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without limitation in the rights to use, copy, modify, merge,
publish, and/ or distribute copies of the Software in an educational or
personal context, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

Permission is granted to sell and/ or distribute copies of the Software in
a commercial context, subject to the following conditions:
Substantial changes: adding, removing, or modifying large parts, shall be
developed in the Software. Reorganizing logic in the software does not warrant
a substantial change.

This project and source code may use libraries or frameworks that are
released under various Open-Source licenses. Use of those libraries and
frameworks are governed by their own individual licenses.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.

Created At: 23:50 - 23/11/2025
*/

/// A type alias for the response returned by command processing functions.
///
/// `Response` is defined as a `String` and is used to represent
/// the output or message generated by the application in response to user input.
///
/// # Example
///
/// ```
/// let resp: Response = String::from("Hello, Rustacean!");
/// ```
type Response = String;

/// Processes a user command passed as a command-line argument and logs the result.
///
/// # Panics
///
/// If no command-line argument is provided (expects a username or command).
///
/// # Example
/// ```
/// // Run the program with a command-line argument:
/// // cargo run -- <username>
/// ```
pub fn simple_cmd_program() {
    let message = std::env::args()
        .nth(1)
        .expect("Enter your username. Usage: language_foundation <message>");

    let info = process_command(&message);

    println!("{}", info);
}

/// The function constructs a greeting message by prepending "Hi, " and appending " Rustacean!"
/// to the provided command string, then returns it as a `Response`.
///
/// # Arguments
///
/// * `cmd` - A string slice representing the command or username to include in the greeting.
///
/// # Returns
///
/// * `Response` - The constructed greeting message.
///
/// # Example
///
/// ```
/// let resp = process_command("Ferris");
/// assert_eq!(resp, Response::from("\nHi, <Ferris> Rustacean!\n"));
/// ```
fn process_command(cmd: &str) -> Response {
    let mut response = Response::from("\nHi, ");
    response.push_str(cmd);

    let mut response = response.replacen(cmd, &format!("<{}>", cmd), 1);
    response.push_str(" Rustacean!");
    response.push('\n');
    response
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn process_command_with_positive_case() {
        let result = process_command("DevopsThinh");
        assert_eq!(result, "\nHi, <DevopsThinh> Rustacean!\n");
    }
}
